version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: go_backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - ./backend/.env
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=app_db
      # - DATABASE_URL
    volumes:
      - ./backend:/app/src
      - ./backend/.env:/app/.env 
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: react_frontend
    ports:
    - "4173:4173"
    volumes:
      - ./frontend:/app/src
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  db_data:
